import {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Tags,
  Layers,
  Ruler,
  GitBranch,
  Barcode,
  Warehouse,
  ArrowLeftRight,
  SlidersHorizontal,
  Send,
  PackageX,
  Receipt,
  ListOrdered,
  Truck,
  Banknote,
  CircleDollarSign,
  PieChart,
  Users,
  ShieldCheck,
  Store,
  Boxes,
  CreditCard,
  Bell,
  ScrollText,
  Settings,
} from 'lucide-react'

export const NAVIGATION = [
  {
    section: null,
    items: [
      { key: 'dashboard', label: 'nav.dashboard', path: '/dashboard', icon: LayoutDashboard },
      { key: 'pos', label: 'nav.pos', path: '/pos', icon: ShoppingCart },
    ],
  },
  {
    section: 'nav.catalog',
    items: [
      {
        key: 'catalog',
        label: 'nav.catalog',
        path: '/products',
        icon: Package,
        permission: 'products.view',
        children: [
          { key: 'products', label: 'nav.products', path: '/products', permission: 'products.view' },
          { key: 'categories', label: 'nav.categories', path: '/categories', permission: 'categories.view' },
          { key: 'brands', label: 'nav.brands', path: '/brands', permission: 'products.view' },
          { key: 'units', label: 'nav.units', path: '/units', permission: 'products.view' },
          { key: 'variants', label: 'nav.variants', path: '/variants', permission: 'products.view' },
          { key: 'barcodes', label: 'nav.barcodes', path: '/barcodes', permission: 'products.view' },
        ],
      },
    ],
  },
  {
    section: 'nav.inventory',
    items: [
      {
        key: 'inventory',
        label: 'nav.inventory',
        path: '/inventory',
        icon: Warehouse,
        permission: 'inventory.view',
        children: [
          { key: 'stock-overview', label: 'nav.stockOverview', path: '/inventory', permission: 'inventory.view' },
          { key: 'movements', label: 'nav.movements', path: '/inventory/movements', permission: 'inventory.view' },
          { key: 'adjustments', label: 'nav.adjustments', path: '/inventory/adjustments', permission: 'inventory.adjust' },
          { key: 'transfers', label: 'nav.transfers', path: '/inventory/transfers', permission: 'inventory.transfer' },
          { key: 'low-stock', label: 'nav.lowStock', path: '/inventory/low-stock', permission: 'inventory.view' },
          { key: 'valuation', label: 'nav.valuation', path: '/inventory/valuation', permission: 'inventory.view' },
        ],
      },
    ],
  },
  {
    section: 'nav.purchasing',
    items: [
      { key: 'purchases', label: 'nav.purchases', path: '/purchases', icon: ListOrdered, permission: 'purchases.view' },
      { key: 'suppliers', label: 'nav.suppliers', path: '/suppliers', icon: Truck, permission: 'suppliers.view' },
    ],
  },
  {
    section: 'nav.selling',
    items: [
      { key: 'sales', label: 'nav.sales', path: '/sales', icon: Receipt, permission: 'sales.view' },
      { key: 'returns', label: 'nav.returns', path: '/sales/returns', icon: ArrowLeftRight, permission: 'sales.return' },
      { key: 'customers', label: 'nav.customers', path: '/customers', icon: Users, permission: 'customers.view' },
      { key: 'cash-register', label: 'nav.cashRegister', path: '/cash-register', icon: Banknote, permission: 'cash_register.open' },
      { key: 'expenses', label: 'nav.expenses', path: '/expenses', icon: CircleDollarSign, permission: 'expenses.view' },
    ],
  },
  {
    section: 'nav.reports',
    items: [
      {
        key: 'reports',
        label: 'nav.reports',
        path: '/reports/sales',
        icon: PieChart,
        permission: 'reports.view',
        children: [
          { key: 'report-sales', label: 'nav.reportSales', path: '/reports/sales', permission: 'reports.view' },
          { key: 'report-purchases', label: 'nav.reportPurchases', path: '/reports/purchases', permission: 'reports.view' },
          { key: 'report-inventory', label: 'nav.reportInventory', path: '/reports/inventory', permission: 'reports.view' },
          { key: 'report-profit', label: 'nav.reportProfit', path: '/reports/profit', permission: 'reports.view' },
          { key: 'report-financial', label: 'nav.reportFinancial', path: '/reports/financial', permission: 'reports.view' },
        ],
      },
    ],
  },
  {
    section: 'nav.administration',
    items: [
      { key: 'users', label: 'nav.users', path: '/users', icon: Users, permission: 'users.view' },
      { key: 'roles', label: 'nav.roles', path: '/roles', icon: ShieldCheck, permission: 'roles.view' },
      { key: 'branches', label: 'nav.branches', path: '/branches', icon: Store, permission: 'settings.view' },
      { key: 'warehouses', label: 'nav.warehouses', path: '/warehouses', icon: Boxes, permission: 'inventory.view' },
      { key: 'registers', label: 'nav.registers', path: '/registers', icon: CreditCard, permission: 'settings.view' },
      { key: 'notifications', label: 'nav.notifications', path: '/notifications', icon: Bell, permission: null },
      { key: 'audit-logs', label: 'nav.auditLogs', path: '/audit-logs', icon: ScrollText, permission: 'audit.view' },
    ],
  },
  {
    section: null,
    items: [
      { key: 'settings', label: 'nav.settings', path: '/settings', icon: Settings, permission: 'settings.view' },
    ],
  },
]

export const ICON_MAP = {
  LayoutDashboard,
  ShoppingCart,
  Package,
  Tags,
  Layers,
  Ruler,
  GitBranch,
  Barcode,
  Warehouse,
  ArrowLeftRight,
  SlidersHorizontal,
  Send,
  PackageX,
  Receipt,
  ListOrdered,
  Truck,
  Banknote,
  CircleDollarSign,
  PieChart,
  Users,
  ShieldCheck,
  Store,
  Boxes,
  CreditCard,
  Bell,
  ScrollText,
  Settings,
}
