export const PERMISSION_GROUPS = [
  {
    key: 'products',
    label: 'Products',
    permissions: [
      { key: 'products.view', label: 'View Products' },
      { key: 'products.create', label: 'Create Products' },
      { key: 'products.update', label: 'Update Products' },
      { key: 'products.delete', label: 'Delete Products' },
    ],
  },
  {
    key: 'categories',
    label: 'Categories',
    permissions: [
      { key: 'categories.view', label: 'View Categories' },
      { key: 'categories.create', label: 'Create Categories' },
      { key: 'categories.update', label: 'Update Categories' },
      { key: 'categories.delete', label: 'Delete Categories' },
    ],
  },
  {
    key: 'inventory',
    label: 'Inventory',
    permissions: [
      { key: 'inventory.view', label: 'View Inventory' },
      { key: 'inventory.adjust', label: 'Adjust Stock' },
      { key: 'inventory.transfer', label: 'Transfer Stock' },
    ],
  },
  {
    key: 'purchases',
    label: 'Purchases',
    permissions: [
      { key: 'purchases.view', label: 'View Purchases' },
      { key: 'purchases.create', label: 'Create Purchases' },
      { key: 'purchases.update', label: 'Update Purchases' },
      { key: 'purchases.receive', label: 'Receive Purchases' },
    ],
  },
  {
    key: 'suppliers',
    label: 'Suppliers',
    permissions: [
      { key: 'suppliers.view', label: 'View Suppliers' },
      { key: 'suppliers.create', label: 'Create Suppliers' },
      { key: 'suppliers.update', label: 'Update Suppliers' },
      { key: 'suppliers.delete', label: 'Delete Suppliers' },
    ],
  },
  {
    key: 'sales',
    label: 'Sales',
    permissions: [
      { key: 'sales.view', label: 'View Sales' },
      { key: 'sales.create', label: 'Create Sales' },
      { key: 'sales.cancel', label: 'Cancel Sales' },
      { key: 'sales.return', label: 'Process Returns' },
    ],
  },
  {
    key: 'customers',
    label: 'Customers',
    permissions: [
      { key: 'customers.view', label: 'View Customers' },
      { key: 'customers.create', label: 'Create Customers' },
      { key: 'customers.update', label: 'Update Customers' },
      { key: 'customers.delete', label: 'Delete Customers' },
    ],
  },
  {
    key: 'expenses',
    label: 'Expenses',
    permissions: [
      { key: 'expenses.view', label: 'View Expenses' },
      { key: 'expenses.create', label: 'Create Expenses' },
      { key: 'expenses.update', label: 'Update Expenses' },
    ],
  },
  {
    key: 'reports',
    label: 'Reports',
    permissions: [
      { key: 'reports.view', label: 'View Reports' },
      { key: 'reports.export', label: 'Export Reports' },
    ],
  },
  {
    key: 'pos',
    label: 'Point of Sale',
    permissions: [
      { key: 'pos.open', label: 'Open Register' },
      { key: 'pos.hold', label: 'Hold Sales' },
      { key: 'pos.discount', label: 'Apply Discounts' },
    ],
  },
  {
    key: 'users',
    label: 'Users',
    permissions: [
      { key: 'users.view', label: 'View Users' },
      { key: 'users.create', label: 'Create Users' },
      { key: 'users.update', label: 'Update Users' },
      { key: 'users.delete', label: 'Delete Users' },
    ],
  },
  {
    key: 'roles',
    label: 'Roles & Permissions',
    permissions: [
      { key: 'roles.view', label: 'View Roles' },
      { key: 'roles.update', label: 'Update Roles' },
    ],
  },
  {
    key: 'settings',
    label: 'Settings',
    permissions: [
      { key: 'settings.view', label: 'View Settings' },
      { key: 'settings.update', label: 'Update Settings' },
    ],
  },
  {
    key: 'audit',
    label: 'Audit Logs',
    permissions: [{ key: 'audit.view', label: 'View Audit Logs' }],
  },
  {
    key: 'cash_register',
    label: 'Cash Register',
    permissions: [
      { key: 'cash_register.open', label: 'Open Register' },
      { key: 'cash_register.close', label: 'Close Register' },
    ],
  },
]

export const ALL_PERMISSIONS = PERMISSION_GROUPS.flatMap((group) =>
  group.permissions.map((permission) => permission.key),
)

export const PERMISSIONS = {
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  CATEGORIES_VIEW: 'categories.view',
  CATEGORIES_CREATE: 'categories.create',
  CATEGORIES_UPDATE: 'categories.update',
  CATEGORIES_DELETE: 'categories.delete',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  PURCHASES_VIEW: 'purchases.view',
  PURCHASES_CREATE: 'purchases.create',
  PURCHASES_UPDATE: 'purchases.update',
  PURCHASES_RECEIVE: 'purchases.receive',
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_UPDATE: 'suppliers.update',
  SUPPLIERS_DELETE: 'suppliers.delete',
  SALES_VIEW: 'sales.view',
  SALES_CREATE: 'sales.create',
  SALES_CANCEL: 'sales.cancel',
  SALES_RETURN: 'sales.return',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_UPDATE: 'customers.update',
  CUSTOMERS_DELETE: 'customers.delete',
  EXPENSES_VIEW: 'expenses.view',
  EXPENSES_CREATE: 'expenses.create',
  EXPENSES_UPDATE: 'expenses.update',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  POS_OPEN: 'pos.open',
  POS_HOLD: 'pos.hold',
  POS_DISCOUNT: 'pos.discount',
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  ROLES_VIEW: 'roles.view',
  ROLES_UPDATE: 'roles.update',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_UPDATE: 'settings.update',
  AUDIT_VIEW: 'audit.view',
  CASH_REGISTER_OPEN: 'cash_register.open',
  CASH_REGISTER_CLOSE: 'cash_register.close',
}

export const ROLE_PERMISSIONS = {
  'admin': ['*'],
  'manager': [
    'products.view', 'products.create', 'products.update',
    'categories.view', 'categories.create', 'categories.update',
    'inventory.view', 'inventory.adjust', 'inventory.transfer',
    'purchases.view', 'purchases.create', 'purchases.update', 'purchases.receive',
    'suppliers.view', 'suppliers.create', 'suppliers.update',
    'sales.view', 'sales.create', 'sales.cancel', 'sales.return',
    'customers.view', 'customers.create', 'customers.update',
    'expenses.view', 'expenses.create', 'expenses.update',
    'reports.view', 'reports.export',
    'pos.open', 'pos.hold', 'pos.discount',
    'users.view',
    'roles.view',
    'settings.view', 'settings.update',
    'audit.view',
    'cash_register.open', 'cash_register.close',
  ],
  'cashier': [
    'products.view',
    'inventory.view',
    'sales.view', 'sales.create', 'sales.return',
    'customers.view', 'customers.create',
    'pos.open', 'pos.hold',
    'cash_register.open', 'cash_register.close',
  ],
  'accountant': [
    'products.view',
    'inventory.view',
    'purchases.view',
    'sales.view',
    'expenses.view', 'expenses.create', 'expenses.update',
    'reports.view', 'reports.export',
    'settings.view',
  ],
  'viewer': ['products.view', 'inventory.view', 'sales.view', 'purchases.view', 'reports.view'],
}
